sudo: required

language: node_js
node_js:
  - "8"


branches:
  only:
    - master

addons:
  chrome: stable

cache:
  directories:
    - "node_modules"

install:
  - npm install

before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start

script:
  - npm run travis-tests