---
# This playbook creates the Docker image and runs a container from it.

- name: Start Docker
  service: name=docker state=started

- name: Build Docker image
  docker_image:
    name: furkleindustries-homepage
    path: /etc/furkleindustries-homepage/

- name: Run Docker container
  docker_container:
    name: furkleindustries-homepage
    image: furkleindustries-homepage
    volumes:
      - /etc/letsencrypt/keys/live/furkleindustries.com/:/etc/furkleindustries-homepage/secrets/
    published_ports:
      - 443:3000