<?php
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST, GET, OPTIONS');

$walkthrough = [
	"assignment-1-start" => "return 'GO INSIDE. IT IS NOT SAFE OUTSIDE. BE A SPY STUDENT, PLEASE.';",
	"assignment-1-indoors" => "return 'YOU DON\u0027T REALLY NEED HELP ALREADY, DO YOU?';",
	"assignment-1-i-am-trainee" => "return 'YOU ARE ABLE TO GO BACK UPSTAIRS WITHOUT A DEVICE, BUT YOU WILL NOT BE ABLE TO BEGIN THE MISSION WITHOUT EQUIPMENT.';",
	"assignment-1-loadout-3" => "return 'SELECT YOUR CHOICE OF ANY WEAPON. EACH WILL HELP YOU TO COMPLETE YOUR FIRST MISSION IN DIFFERENT WAYS. (IF YOU WERE WONDERING, THE GUN IS DELIBERATELY IMPOSSIBLE TO PICK UP. YOU\u0027LL HAVE TO CHOOSE A DIFFERENT ITEM.)';",
	"..." => "return 'THERE APPEARS TO BE A SLIGHT PROBLEM WITH THE GUN AT THE MOMENT. YOU WILL HAVE TO MAKE ANOTHER SELECTION.';",
	"assignment-1-horizon" => "return 'THERE IS NOTHING OF INTEREST IN THIS DIRECTION. THE ONLY WAY TO GO IS FORWARD.';",
	"assignment-1-approach-1" => "return 'IN ORDER TO PASS THIS AREA, WALK CLOSER. DO NOT PICK UP THE ROCK IN THIS PASSAGE, BECAUSE IT WILL EXPLODE AND KILL YOU.';",
	"assignment-1-fake-rock-pickup" => "return 'THERE IS NOT A GREAT DEAL I CAN DO TO HELP YOU AT THIS POINT. YOU PICKED UP THE ROCK YOU WEREN\u0027T SUPPOSED TO PICK UP. NOW IT EXPLODED YOU AND YOU ARE DEAD. START OVER OR GO BACK, I GUESS.';",
	"assignment-1-approach-2" => "return 'PICKING UP THE NORMAL ROCK WILL ENABLE YOU TO ENTER THE FACILITY. WALKING CLOSER WILL RESULT IN YOUR DEATH.';",
	"assignment-1-hallway" => "return 'WALKING TOWARDS THE DATACORE BEFORE ENTERING THE BREAK ROOM WILL ALWAYS RESULT IN YOUR DEATH. THERE ARE THINGS YOU HAVE TO DO IN THE BREAK ROOM FIRST.';",
	"assignment-1-break-room" => "switch (window.equipment) { case 'BANANA': return 'GO TO EAT THE BANANA BREAD, THEN HACK THE BANANA BREAD.'; case 'BRA': return 'SIT AT THE TABLE AND WAIT FOR THE HOT STUFF TO START.'; case 'OATMEAL': return 'ENTER THE LOCKER, PLACE THE OATMEAL ON THE FLOOR, SIT AT THE TABLE.'; case 'NONE': return 'ENTER THE LOCKER, PUT ON THE BIRD SUIT, EXIT THE LOCKER, PUT THE SIGN ON THE DOOR, SIT AT THE TABLE.'; default: return 'IT LOOKS LIKE THE EQUIPMENT VARIABLE HAS AN UNEXPECTED VALUE! I DON\u0027T KNOW HOW THAT COULD\u0027VE HAPPENED, BUT YOU\u0027RE PROBABLY BETTER OFF RESTARTING YOUR GAME.'; }",
	"assignment-1-datacore-keypad-entry" => "return 'THE PASSWORD IS \u0027UPDOG\u0027. THE DIRECTION OF HEAVEN, THE OPPOSITE OF GOD. GET IT? GET IT?';",
	"assignment-1-datacore-final-choice-1" => "return 'THERE ARE ONLY TWO OPTIONS HERE. ALL BUT ONE OF THE LINKS TAKES YOU TO ONE OPTION, AND A SINGLE LINK TAKES YOU TO THE OTHER.';",
	"assignment-2-orbit-2" => "return 'DON'T CLICK THE INSCRUTABLY LABELED BUTTON IF YOU WANT TO LIVE.';",
	"assignment-2-orbit-self-destruct-death" => "return 'I TOLD YOU NOT TO CLICK THE INSCRUTABLY LABELED BUTTON. NOW YOU'RE GOING TO DIE.';",
	"assignment-2-bad-noise" => "return 'MAYBE I DON'T HAVE TO TELL YOU THIS, BUT EJECTING FROM A ROCKET WHICH IS CURRENTLY EXITING THE EARTH'S ATMOSPHERE IS PROBABLY A BAD IDEA.';",
	"assignment-2-bad-noise-eject-death" => "return 'I GUESS I HAVE TO TELL YOU. TWICE, IN FACT. EJECTING FROM A ROCKET WHICH IS CURRENTLY EXITING THE EARTH'S ATMOSPHERE IS A BAD IDEA.';",
	"assignment-2-bad-trajectory-4" => "return 'BOTH ATTEMPTING TO HACK THE ROCKET AND SITTING BACK AND WAITING WILL LEAD TO THE SAME DEATH PASSAGE. PERFORMING PERCUSSIVE MAINTENANCE WILL ALLOW YOU TO REPAIR THE ROCKET.';",
	"assignment-2-bad-trajectory-punch" => "return 'YOU HAVE TO PERFORM ALL THREE PUNCH ACTIONS TO PROGRESS.';",
	"assignment-2-okay-unconscious" => "return 'ALL OF THESE OPTIONS WILL ALLOW YOU TO PROCEED. IT'S OKAY TO THINK ABOUT WHATEVER YOU LIKE.';",
	"assignment-2-okay-fall-down" => "return 'HEALING OR REPAIRING YOUR LEG WILL BOTH ALLOW YOU TO PROCEED. CALLING AAA WILL RESULT IN YOUR DEATH.';",
	"assignment-2-okay-heal-leg-4" => "return 'WORK ON YOUR STUPID SHITTY BLEEDING LEG IF YOU WANT TO LIVE. THE WORK OF LIFE IS OFTEN UNPLEASANT AND BORING, OKAY?';"
];

echo json_encode($walkthrough);
?>
